version: '3.3'

services:
  cubitwelve-db:
    image: mysql:8.0.29
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      SERVICE_NAME: cubitwelve-db
    ports:
      - 3306:3306
    expose:
      - '3306'
    volumes:
      - cubitwelve-db:/var/lib/mysql

volumes:
  cubitwelve-db:
